[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "cd orchestrator",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd orchestrator",
  "pnpm run build"
]

[start]
cmd = "cd orchestrator && pnpm run start"

